# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'millennial-3'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 'UA-112060364-2'

menu:
- {name: 'ABOUT',              url: '/about'}
- {name: 'RESUME',              url: 'https://drive.google.com/file/d/1KxsNz5D_WkZmqZj1OFh0Vtzgzd1FTokS/view?usp=sharing', external: true}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'linkedin', link:   'https://www.linkedin.com/in/sb-fuller-studio/'}
- {icon: 'github', link:   'https://github.com/sbfullerstudio'}
- {icon: 'envelope', link:   'mailto:sbfullerstudio@gmail.com'}

# - {icon: 'rss-square', link: 'rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

post_date_prefix: 'Written on'
